import ClientAuthProvider from "@/lib/ClientAuthProvider";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800 min-h-screen min-w-screen">
        <ClientAuthProvider>{children}</ClientAuthProvider>
      </body>
    </html>
  );
}
