import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import ClientContextProvider from "@/client/context";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <ClientContextProvider>
        <body className="bg-slate-800 min-h-screen min-w-screen">
          {children}
        </body>
      </ClientContextProvider>
    </html>
  );
}
